config/routes.rb
Rails.application.routes.draw do
 
  resources :whispers, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end
  
  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  root 'top#index'
end

app/models/whisper.rb
class Whisper < ActiveRecord::Base
    validates :content, presence: true
    validates :content, length: { in: 1..140 }  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:edit, :update, :destroy]
  
  def new
    if params[:back]
      @contact = Contact.new(contact_params)
    else
      @contact =  Contact.new
    end
  end
 
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
    redirect_to new_contact_path, notice: "ささやきありがとうございました
    
    
    
    ！"
    else
    #入力フォームを再描画。
    render action: 'new'
    end
  end

  def confirm
    @contact = Contact.new(contact_params)
    render :new if @contact.invalid?
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :mail_address, :content)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/whispers_controller.rb
class WhispersController < ApplicationController
  before_action :set_whisper, only: [:edit, :update, :destroy]
  
  def index
    @whispers = Whisper.all
  end
  
  def new
    if params[:back]
      @whisper = Whisper.new(whispers_params)
    else
      @whisper = Whisper.new
    end
  end
  
  def create
    @whisper = Whisper.new(whispers_params)
    if @whisper.save
     redirect_to whispers_path, notice: "ささやきました！"
    else
    #入力フォームを再描画。
     render action: 'new'
    end
  end
 
  def edit
    @whisper = Whisper.find(params[:id])
  end
  
  def update
    @whisper = Whisper.find(params[:id])
    if @whisper.update(whispers_params)
      redirect_to whispers_path, notice: "ささやきを削除しました！"
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @whispers = Whisper.find(params[:id])
    @whisper.destroy
    redirect_to whispers_path, notice: "ささやきを削除しました！"
  end
  
  def confirm
    @whisper = Whisper.new(whispers_params)
    render :new if @whisper.invalid?
  end
  
  private
    def whispers_params
      params.require(:whisper).permit(:title, :content)
    end
    
    def set_whisper
      @whisper = Whisper.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/whispers_helper.rb
module WhispersHelper
    def choose_new_or_edit
      if action_name == 'new' || action_name == 'confirm'
        confirm_whispers_path
      elsif action_name == 'edit'
        whispers_path
      end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
   <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Whisper", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ささやく", new_whisper_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "ささやきリスト", whispers_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
 
    
    
    
  </header>
</body>
<%= yield %>

　<footer>
      <p> Team whisper for Ruby</p>
      <p>2016-2017 copyright creapphere co.ltd</p>
  </footer>

</html>

app/views/top/index.html.erb
<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Whisper</title>
    <link rel="stylesheet" href="style.css">    
    <link rel="stylesheet" href="normalize.css">
</head>
 <section class="main-header">
    <img src="<%= asset_path "ruby.png" %>">
    <img src="<%= asset_path "whisper.png" %>">
  </section>
</head>
  
  
  <section class="about">
    <h1>About Whisper</h1>
    <p>
       Whisperは、Rubyを勉強している人たちのささややきのアプリです。<br>
       みんなでささやいてつながりましょう。
    </p>
   
  </section>
   <section class="function container-fluid">
    <div class="row">
        
      <div class="col-md-offset-1 col-md-3 col-sm-6">
        <img class="key" src="<%= asset_path "key.png" %>">
        
       <p> ログイン</p>
    </div>
    
    <div class="col-md-3 col-sm-6">
      <img class="mail" src="<%= asset_path "mail.png" %>">
       <p> メール送信</p>
    </div> 
     <div class="col-md-3 col-sm-6">
       <img class="comment" src="<%= asset_path "comment1.png" %>">
      <p> ささやき投稿</p>
</div>   
 
  </div>
  </section>
</body>
</html>
<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

app/views/whispers/_form.html.erb
<%= form_for(@whisper, url: choose_new_or_edit) do |f| %>
  <% if @whisper.errors.any? %>
    <div id="error_explanation">
      <h2><%= @whisper.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @whisper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
    <%= f.label :ささやき %>
    <%= f.text_field :content, class: 'form-control' %>
  <br>
    <%= f.submit 'ささやく', class: 'btn btn-danger active btn-block' %>
  <% end %>

<%= link_to "ささやきリストにもどる", whispers_path %>

app/views/whispers/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

   <h3>以下の内容で、送信する。</h3>
   <%= form_for(@whisper) do |f| %>
   <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
    <%= f.hidden_field :title %>
    <%= f.hidden_field :content %>

  <!-- @whisper.titleと@whisper.contentとすることで、表示用の値を画面に出力しています。 -->
    <p>タイトル:<%= @whisper.title %></p>
    <p>本文:<%= @whisper.content %></p>
    <%= f.submit "ささやく",class: 'btn btn-primary btn-block' %>
  <% end %>

 <%= form_for(@whisper, url: new_whisper_path, method: 'get') do |f| %>
    <%= f.hidden_field :title %>
    <%= f.hidden_field :content %>
    <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
  <% end %>
 </div>
</div>

app/views/whispers/edit.html.erb
<%= form_for(@whisper, url: confirm_whispers_path ) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
<% end %>



<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ささやく</h2>
    <%= render 'form' %>
  </div>
</div>
<%= render 'form' %>

app/views/whispers/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>ささやきリスト</h1>
      <%= link_to "ささやく", new_whisper_path, class: 'btn btn-default btn-sm btn-danger active' %>
      <% @whispers.each do |whisper| %>
    <div class="row">
      <h4><strong><%= whisper.title %></strong></h4>
      <p><%= whisper.content %></p>
      <%= link_to "編集", edit_whisper_path(whisper.id), class: 'btn btn-default btn-sm btn-danger active' %>
      <%= link_to "削除", whisper_path(whisper.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-warning active' %>
    </div>
    <% end %>
  </div>
</div>

app/views/whispers/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
  
<h2>Whisper</h2>

<%= render 'form' %>

  </div>
</div>